Gettext
qa-dev/wda-inspector pull request #6
Opened 2016-10-12 08:15 UTC by Enapiuz

2016-10-12 08:21 UTC, makhov requested changes

2016-10-12 08:21 UTC, makhov commented on wda/gettext.go
> +	var textResp *GetTextResponse
здесь 
`var textResp GetTextResponse `
а внизу
`return &textResp, nil`

2016-10-12 08:21 UTC, makhov commented on handlers/gettext.go
> +func (h *GetTextHandler) get(elementId string) (*wda.GetTextResponse, error) {
Не лучшее имя для метода

2016-10-12 08:21 UTC, makhov commented on main.go
> +	mux.Handle("/get-text", middleware.New(handlers.NewGetTextHandler(iClient)))
я бы по аналогии с JsonWire использовал camelCase

2016-10-12 08:24 UTC, Enapiuz commented on handlers/gettext.go
> +func (h *GetTextHandler) get(elementId string) (*wda.GetTextResponse, error) {
что-то типа getText лучше будет или не в ту сторону смотрю?

2016-10-12 17:30 UTC, makhov commented on handlers/gettext.go
> +func (h *GetTextHandler) get(elementId string) (*wda.GetTextResponse, error) {
Да. Но, например, наши гоферы юзают что-то типо `getTextResult`. У тебя возвращается `response`, можно, например `getTextResponse`

2016-10-13 07:13 UTC, makhov approved these changes

2016-10-13 09:01 UTC, merged