Extracting client + test
qa-dev/wda-inspector pull request #7
Opened 2016-10-13 20:43 UTC by Enapiuz

2016-10-13 20:43 UTC, Enapiuz commented on wda/interface.go
> +	BundleId() string
Вот тут не очень уверен, надо утром будет посмотреть

2016-10-14 06:22 UTC, Enapiuz commented on wda/interface.go
> +	BundleId() string
а нет, без него никак

2016-10-18 06:49 UTC, Enapiuz commented on wda/interface.go
> +	BundleId() string
Хотя очень даже как :)

2016-10-18 06:53 UTC, makhov requested changes
Вроде все ок, надо только чуть реорганизовать код

2016-10-18 06:53 UTC, makhov commented on wda/gettext_test.go
> +		res = "{\"value\": \"FakeText\", \"status\": 0}"
На будущее – можно юзать `` ` `` вместо `"` и не придется экранировать + в бэктиках можно переносить на несколько строк

2016-10-18 06:53 UTC, makhov commented on wda/wdaclient.go
> +	return &Client{Client: r, bundleId: bundleId}
Тебе точно нужен Client в структуре публичный? 
И с неймингом надо что-то решать, лучше уж так же назвать Requester, чем иметь 2 разных `Client`. Ну или тупо httpClient

2016-10-18 06:53 UTC, makhov commented on wda/httpclient.go
> +package wda
Это можно вынести в отдельный пакет, зачем тебе это в `wda`?

2017-03-12 12:57 UTC, Enapiuz commented
закрою, чтоб не висело почем зря

2017-03-12 12:57 UTC, closed without merging